name: correcto test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 
        uses: aparnajyothi-y/setup-java@grralvm-fix
        with:
          distribution: 'corretto'
          java-version: '8'
          overwrite-settings: true
      
      - name: Check Runner ToolCache
        run: |
          ls -la $RUNNER_TOOL_CACHE/Java_Corretto_jdk/
          
      - name: Setup Java Again
        uses: aparnajyothi-y/setup-java@grralvm-fix
        with:
          distribution: 'corretto'
          java-version: '8'
          overwrite-settings: true
