name: correcto test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8.432.06+1'
          distribution: 'corretto'
          cache: 'maven'

      - name: Setup Java Again
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '8.432.06+1'

      - name: Verify Java version
        run: java -version


      - name: Build with Maven
        run: mvn install
      
