name: Maven Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        server-id: 'github'
 
  
    - name: Build with Maven
      run: mvn -B clean package -U --file pom.xml


    - name: Publish to GitHub Packages
      run: mvn clean deploy 

      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Set up Apache Maven Central
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        server-id: central
        server-username: ${{ secrets.MAVEN_USERNAME }}
        server-password: ${{ secrets.MAVEN_CENTRAL_TOKEN_APARNA }}
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY_APARNA }}
        gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE_APARNA }}

    - name: Publish to Apache Maven Central
      run: mvn deploy
      env:
        MAVEN_USERNAME: KPITZtZH
        MAVEN_CENTRAL_TOKEN: 0AcBJ006VqAqDJ5S/9hyRpP9KfsDj+RMorufAoIyEeL4
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE_APARNA }}
