name: Repro cached JDK25 issue

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 25 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: gradle

      - name: Verify Java
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          which java
          ls -la "$JAVA_HOME/bin"

      - name: Run Gradle build
        run: ./gradlew clean build --no-daemon
