name: test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: aparnajyothi-y/setup-java@fix-punycode-warning-deprication
        with:
          java-version: '17'
          distribution: 'temurin'
        

     
