name: OpenJDK test

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.1'
          distribution: 'microsoft'
          java-package: 'jdk'
          cache: 'sbt'

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        run: mvn install
      
