name: Java CI

on: 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: aparnajyothi-y/setup-java@PR#664-test
      with:
        distribution: 'adopt'
        java-version: '17'
        cache: 'maven'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

   
    - name: Install dependencies
      run: mvn install -DskipTests
