name: Test Setup Java with .tool-versions

on: 
  workflow_dispatch:

jobs:
  setup-java:
    runs-on: ubuntu-latest  # Change to macos-latest or windows-latest if testing on other platforms

    steps:
      # Checkout the repository to make .tool-versions accessible
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .tool-versions file with random version
        run: |
          # Define an array of possible versions
          versions=(
            "temurin-21.0.5+11.0.LTS"
            "oracle-17.0.1"
            "corretto-11.0.9.1"
            "openjdk-8.0.292+10"
            "graalvm-19.3.0"
            "zulu-16.0.0.24"
            "redhat-11.0.8.10"
            "temurin-11.0.12+7.LTS"
            "temurin-8.0.292+5"
            "openjdk-16.0.2+7"
            "temurin-14.0.2+12"
          )
      
          # Get a random index
          random_version=${versions[$RANDOM % ${#versions[@]}]}
      
          # Create the .tool-versions file with the random version
          echo "java $random_version" > .tool-versions
      
          # Output the contents to verify it's created correctly
          cat .tool-versions


      # Debug the .tool-versions file
      - name: Verify .tool-versions file contents
        run: cat .tool-versions

      # Use setup-java action to set up Java
      - name: Set up Java using aparnajyothi-y/setup-java@update-regex-toolversion
        id: setup-java
        uses: aparnajyothi-y/setup-java@update-regex-toolversion
        with:
          distribution: "temurin"
          java-version-file: ".tool-versions"

      # Check Java version after setup
      - name: Verify Java version
        run: java -version

      # Debugging the version from setup-java by checking the installation path
      - name: Debug setup-java output
        run: |
          echo "Java home directory: $JAVA_HOME"
          echo "Java version from setup-java:"
          $JAVA_HOME/bin/java -version
