name: Compare Cached vs Fresh JDK25

on:
  workflow_dispatch:

jobs:
  jdk-cache-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 1: Setup JDK25 with Maven cache (cached)
      - name: Setup JDK25 Temurin with Maven cache
        uses: actions/setup-java@v5
        id: cached
        with:
          distribution: temurin
          java-version: 25
          cache: maven
          cache-dependency-path: pom.xml

      - name: Inspect cached JDK
        run: |
          echo "Listing all files in cached JDK..."
          ls -lR $JAVA_HOME > cached-jdk-files.txt
          echo "Computing SHA-256 checksums for cached JDK..."
          find $JAVA_HOME -type f -exec sha256sum {} \; > cached-jdk.sha256

      - name: Download fresh JDK25 Temurin
        run: |
          FRESH_DIR="$RUNNER_TEMP/fresh-jdk25"
          mkdir -p $FRESH_DIR
          echo "Downloading fresh JDK25..."
          curl -L -o $FRESH_DIR/jdk25.tar.gz https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.0+36/OpenJDK25U-jdk_x64_linux_hotspot_25.0.0_36.tar.gz
          echo "Extracting JDK25..."
          tar -xzf $FRESH_DIR/jdk25.tar.gz -C $FRESH_DIR --strip-components=1
          echo "Listing files in fresh JDK..."
          ls -lR $FRESH_DIR

      # Step 3: Compare cached vs fresh JDK checksums
      - name: Compare cached vs fresh JDK
        run: |
          echo "Comparing cached and fresh JDK..."
          diff cached-jdk.sha256 fresh-jdk.sha256 || echo "Differences detected - cached JDK is modified!"
