name: Test Java Version 11 jetbrains

on:
 workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

  
      # Step 3: Set up Java with the normalized versions from the 'hidden' input
      - name: Set up Java
        uses: gmitch215/setup-java@main
        with:
          distribution: 'jetbrains'
          java-package: jre+ft
          java-version: '11'
    
