name: Validate Non-Cached Temurin JDK25

on:
  workflow_dispatch:

jobs:
  validate-temurin-noncached:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 24 Temurin
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 24
          cache: 'gradle'
        
      - name: Verify JDK installation
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          java -version
          ls -lR $JAVA_HOME | head -30

      - name: Compute SHA512 checksums for key files
        run: |
          echo "Computing SHA512 for critical JDK files..."
          sha512sum $JAVA_HOME/lib/ct.sym || echo "ct.sym not found"
          sha512sum $JAVA_HOME/lib/jrt-fs.jar || echo "jrt-fs.jar not found"

      - name: Run jlink to trigger validation
        run: |
          echo "Running jlink validation..."
          jlink --version
          jlink --list-plugins
          echo "If you see no 'has been modified' errors, the non-cached JDK is valid."

      - name: Capture JDK structure summary
        run: |
          echo "Capturing JDK directory summary..."
          du -sh $JAVA_HOME
          find $JAVA_HOME/lib -maxdepth 1 -type f

      - name: Upload JDK info artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: temurin25-noncached-validation
          path: |
            $JAVA_HOME/lib/ct.sym
            $JAVA_HOME/lib/jrt-fs.jar
