name: Java CI with setup-java v4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest,macos-13]
        

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'semeru'
        java-version: '8'
        
            
    - name: Run tests
      run: mvn test
