name: Repro cached JDK25 issue

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 25 Temurin with Maven cache
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          cache: maven
          cache-dependency-path: pom.xml
          cache-key: setup-java-Linux-x64-maven-80603dcdd65a520fae049babd82899c3be4744177c2a5eb9d9b30f0b5200ee00

      - name: Verify Java
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          which java
          ls -la "$JAVA_HOME/bin"

      - name: Run Maven build
        run: mvn clean install -B
