name: test

on:
  workflow_dispatch:
  
jobs:
  build-and-deploy-v4:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "oracle"
        cache: "maven"


  build-and-deploy-v3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "oracle"
        cache: "maven"
   
     

     
