name: Repro Cached JDK25 Temurin Issue

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 25 Temurin with Gradle cache
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          cache: gradle

      - name: Verify Java version
        run: |
          java -version
          javac -version
