name: Java CI with setup-java v3

on:
  workflow_dispatch:

jobs:
  test_v4:
    runs-on: ubuntu-latest
    name: Testing on Github Runner for temurin sdk
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

  test_v3:
    runs-on: windows-latest
    name: Testing on Github Runner for zulu sdk
    steps:
      - uses: actions/setup-java@v4\3
        with:
          distribution: temurin
          java-version: 17
