name: Repro Cached JDK25 Issue

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 25 Temurin with cache
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          cache: gradle
